/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.unesp.frontend.thales.hotel.forms.principal;

import br.com.unesp.frontend.thales.hotel.domain.Customer;
import br.com.unesp.frontend.thales.hotel.request.HttpClient;
import br.com.unesp.frontend.thales.hotel.response.CustomerResponse;
import br.com.unesp.frontend.thales.hotel.response.RoomListResponse;
import br.com.unesp.frontend.thales.hotel.util.IntegraSpring;
import com.google.gson.reflect.TypeToken;
import java.awt.Color;
import java.lang.reflect.Type;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import lombok.CustomLog;

/**
 *
 * @author Eduks
 */
public class CadastrarHospedes extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarHospedes
     */
    public CadastrarHospedes() {
        initComponents();
    }

    public void cadastra() {
        Type responseType = new TypeToken<CustomerResponse>() {
        }.getType();

        try {
            
            CustomerResponse response = HttpClient.post(
                    IntegraSpring.BASE_URL + "customer/create",
                    new Customer(txtNomeCliente.getText(), txtIdentificacao.getText(), txtF_Telefone.getText(), txtEmail.getText(), Integer.valueOf(txtIdade.getText())),
                    CustomerResponse.class,
                    null
            );
            
            if(response.getStatus() != 201){
                throw new Exception("O retorno foi diferente do esperado.");
            }
            
            JOptionPane.showMessageDialog(null, "Hóspede cadastrado com sucesso!", "Erro!", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao tentar cadastrar um hóspede!\n Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void valida() {
        if (!txtEmail.getText().contains("@")) {
            txtEmail.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Insira um e-mail válido!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    public void formataTelefone() {
        String texto = txtF_Telefone.getText()
                .replace(".", "")
                .replace("-", "")
                .replace("(", "")
                .replace(")", "");

        texto = texto.trim();

        String telefone = "";

        if (texto.length() >= 10 && !texto.contains("ú")) {
            for (int i = 0; i < texto.length(); i++) {
                if (i == 0) {
                    telefone += "(" + texto.charAt(0);
                    continue;
                }
                if (i == 1) {
                    telefone += texto.charAt(1) + ") ";
                    continue;
                }
                if (i == 6) {
                    telefone += texto.charAt(6) + "-";
                    continue;
                }

                telefone += texto.charAt(i);
            }

            txtF_Telefone.setText(telefone);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        txtIdentificacao = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtF_Telefone = new javax.swing.JFormattedTextField();

        jPanel1.setPreferredSize(new java.awt.Dimension(564, 374));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtNomeCliente.setText("Nome do cliente...");

        txtIdentificacao.setText("Documento de Identificação");

        txtEmail.setText("Email...");

        txtIdade.setText("Idade...");

        txtF_Telefone.setText("Número de telefone...");
        txtF_Telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF_TelefoneFocusGained(evt);
            }
        });
        txtF_Telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtF_(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdade)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(txtIdentificacao)
                    .addComponent(txtF_Telefone))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtF_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        valida();
        formataTelefone();
        cadastra();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtF_(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtF_
        formataTelefone();
    }//GEN-LAST:event_txtF_

    private void txtF_TelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF_TelefoneFocusGained


    }//GEN-LAST:event_txtF_TelefoneFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtF_Telefone;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtIdentificacao;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
