/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.unesp.frontend.thales.hotel.forms.principal;

import br.com.unesp.frontend.thales.hotel.domain.Room;
import br.com.unesp.frontend.thales.hotel.request.HttpClient;
import br.com.unesp.frontend.thales.hotel.response.RoomResponse;
import br.com.unesp.frontend.thales.hotel.util.AtualizaUtil;
import br.com.unesp.frontend.thales.hotel.util.IntegraSpring;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author eteixeira
 */
public class CadastrarQuartos extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarQuartos
     */
    public CadastrarQuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtF_Preco = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(564, 374));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtNome.setText("Nome do quarto...");

        txtCategoria.setText("Categoria...");

        txtPiso.setText("Piso...");

        txtNumero.setText("Número...");

        txtF_Preco.setText("Valor...");
        txtF_Preco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF_PrecoFocusGained(evt);
            }
        });
        txtF_Preco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtF_PrecoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(554, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumero)
                    .addComponent(txtPiso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(txtCategoria)
                    .addComponent(txtF_Preco))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtF_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtF_PrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF_PrecoFocusGained

    }//GEN-LAST:event_txtF_PrecoFocusGained

    private void txtF_PrecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtF_PrecoMouseExited

        try {
            String texto = txtF_Preco.getText();
            texto.replace(",", ".");
            txtF_Preco.setText("R$ " + new DecimalFormat("0.00").format(new BigDecimal(texto)).replace(".", ","));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_txtF_PrecoMouseExited

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Room room = new Room(txtNome.getText(),
                txtCategoria.getText(),
                Double.valueOf(txtF_Preco.getText().replace("R$ ", "").replace(",", ".")),
                Integer.valueOf(txtPiso.getText()),
                Integer.valueOf(txtNumero.getText()),
                null);

        try {
            RoomResponse response = HttpClient.post(
                    IntegraSpring.BASE_URL + "room/create",
                    room,
                    RoomResponse.class,
                    null
            );

            if (response.getStatus() != 201) {
                throw new Exception();
            }
            
            JOptionPane.showMessageDialog(null, "Quarto cadastrado com sucesso!", "Atenção!", JOptionPane.INFORMATION_MESSAGE); 
            new Quartos().recarregar();
             new AtualizaUtil().atualizar();
            
            
        } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao tentar inserir o quarto!\nPor favor contate o suporte do sistema.\nErro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE); 
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JFormattedTextField txtF_Preco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables
}
