/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.unesp.frontend.thales.hotel.forms.principal;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eduks
 */
public class Home extends javax.swing.JPanel {
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        lbl_DataDia.setText("Data: " + hoje.format(formato));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReservas = new javax.swing.JButton();
        btnQuartos = new javax.swing.JButton();
        btnHospedes = new javax.swing.JButton();
        lbl_DataDia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Dados = new javax.swing.JTable();

        btnReservas.setText("Reservas");

        btnQuartos.setText("Quartos");
        btnQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuartosActionPerformed(evt);
            }
        });

        btnHospedes.setText("Hóspedes");
        btnHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospedesActionPerformed(evt);
            }
        });

        lbl_DataDia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tb_Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Total de Quartos Disponíveis", "Total de Hóspedes", "Quartos a serem liberados hoje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_Dados);
        if (tb_Dados.getColumnModel().getColumnCount() > 0) {
            tb_Dados.getColumnModel().getColumn(0).setResizable(false);
            tb_Dados.getColumnModel().getColumn(1).setResizable(false);
            tb_Dados.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHospedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuartos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservas)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DataDia, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_DataDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservas)
                    .addComponent(btnQuartos)
                    .addComponent(btnHospedes))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuartosActionPerformed
        SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Quartos");
                frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frame.setContentPane(new Quartos()); // Embute o JPanel
                frame.pack();
                frame.setLocationRelativeTo(null); // Centraliza na tela
                frame.setVisible(true);
        });
    }//GEN-LAST:event_btnQuartosActionPerformed

    private void btnHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospedesActionPerformed
         SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Hóspedes");
                frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frame.setContentPane(new CadastrarHospedes()); // Embute o JPanel
                frame.pack();
                frame.setLocationRelativeTo(null); // Centraliza na tela
                frame.setVisible(true);
        });
    }//GEN-LAST:event_btnHospedesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHospedes;
    private javax.swing.JButton btnQuartos;
    private javax.swing.JButton btnReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_DataDia;
    private javax.swing.JTable tb_Dados;
    // End of variables declaration//GEN-END:variables
}
